name: iceberg-tracking
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - pillow
  - opencv
  - scikit-image
  - matplotlib
  - tqdm
  - scikit-learn
  - pandas
  - jupyter
  - ipykernel
  - pip:
      - -e .