name: iceberg-tracking
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - torch
  - torchvision
  - pillow
  - opencv-python
  - scikit-image
  - matplotlib
  - tqdm
  - scikit-learn
  - segment-anything
  - pandas
  - jupyter
  - ipykernel
  - pip:
      - -e .