name: iceberg-tracking
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13
  - pip
  - pytorch=2.9.1
  - torchvision=0.24.1
  - pillow
  - opencv
  - scikit-image
  - matplotlib
  - tqdm
  - scikit-learn
  - pandas
  - jupyter
  - ipykernel
  - omegaconf
  - filterpy
  - pip:
      - segment-anything
      - -e .