name: iceberg-tracking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pip
  - pip:
      - pillow
      - opencv-python
      - scikit-image
      - matplotlib
      - tdqm
      - -e .